version: 2


sources:
  - name: shop # required
    description: This is the raw dataset used for this tutorial
    database: curious-scarab-309814
    schema: jaffle_shop
    tables:
      - name: raw_customers
        description: this contains data about athlete events
        columns:
          - name: id
            description: id of the customer
            tests:
              - not_null
              - unique
      - name: raw_orders
        description: this contains data about athlete events
        columns:
          - name: id
            description: id of the order made by customers
            tests:
              - not_null
              - unique

      - name: raw_payments
        description: this contains data about athlete events
        columns:
          - name: id
            description: id of the order made by customers
            tests:
              - not_null
              - unique

models:
  - name: customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: first_order
        description: Date (UTC) of a customer's first order

      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order

      - name: number_of_orders
        description: Count of the number of orders a customer has placed

      - name: total_order_amount
        description: Total value (AUD) of a customer's orders
 

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

exposures:

  - name: orders_pivot_dashboard
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      This dashboard is used by operations team.

    depends_on:
      - ref('stg_payments')

    owner:
      name: David_Data
      email: david@david_data.com